#!/bin/bash

PLUGINS=(
  bkad/CamelCaseMotion
  Raimondi/delimitMate
  morhetz/gruvbox
  ervandew/supertab
  vim-airline/vim-airline
  tpope/vim-commentary
  machakann/vim-highlightedyank
  michaeljsmith/vim-indent-object
  tpope/vim-pathogen
  sheerun/vim-polyglot
  tpope/vim-repeat
  tpope/vim-surround
)


set -e
cd "$(dirname "$0")/.."


# Install or update listed plugins

for repo in "${PLUGINS[@]}" ; do
  plugin_dir="_vim/bundle/${repo#*/}"
  printf "\e[33m${repo}:\e[0m "

  if [ ! -e "$plugin_dir" ] ; then
    # new plugin, install it
    git clone "https://github.com/${repo}.git" "$plugin_dir"
  else
    # existing plugin, update it
    ( cd "$plugin_dir" && git pull --ff-only )
  fi

  # fetch or update submodules if necessary
  ( cd "$plugin_dir" && git submodule update --init --recursive )
done


# Update help tags

vim +Helptags +q
