#!/bin/bash

PLUGINS=(
  altercation/vim-colors-solarized
  derekwyatt/vim-scala
  ervandew/supertab
  kchmck/vim-coffee-script
  michaeljsmith/vim-indent-object
  morhetz/gruvbox
  mxw/vim-jsx
  pangloss/vim-javascript
  Raimondi/delimitMate
  tpope/vim-commentary
  tpope/vim-pathogen
  tpope/vim-repeat
  tpope/vim-surround
  tpope/vim-unimpaired
  vim-airline/vim-airline
)


set -e
cd "$(dirname "$0")/.."


# Install or update listed plugins

for repo in "${PLUGINS[@]}" ; do
  plugin_dir="_vim/bundle/${repo#*/}"
  printf "\e[33m${repo}:\e[0m "

  if [ ! -e "$plugin_dir" ] ; then
    # new plugin, install it
    git clone "https://github.com/${repo}.git" "$plugin_dir"
  else
    # existing plugin, update it
    ( cd "$plugin_dir" && git pull )
  fi

  # fetch or update submodules if necessary
  ( cd "$plugin_dir" && git submodule update --init --recursive )
done


# Update help tags

vim +Helptags +q
